spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/API_PRODUCTO_SPRING_FOR_GRAPHQL
  graphql:
    graphiql:
      enabled: true

logging:
  level:
    root: INFO
    com.fredgar.pe.controller: WARN
    com.fredgar.pe.service.logic: WARN